### ISSUE TITLE
Find examples of 10 list web sites

### ISSUE THREAD

**Issue by dudarev** [gromadco/change-password-links#1]
Some examples:
- https://nomadlist.io/
- http://osgameclones.com/
- http://startupmovies.be-genius.com

Find 5 more example and mention them in the comments below.

**Comment by dudarev** [comment]
@betula-pendula when done re-direct to @serejahh 
@serejahh when done redirect to me

**Comment by betula-pendula** [comment]
examples of sites. What are suitable and which are not on this list?

http://www.imdb.com/list/ls055592025/ (100 best films)
http://best-links.net.ru
http://top100.rambler.ru/navi/?theme=1
http://ua-ix.biz
http://edu-top.ru/katalog/
http://bit2bit.cc
http://www.geogr.msu.ru/cafedra/geom/links/

**Comment by dudarev** [comment]
They all look good. So I'm adding these two:
- http://urli.st/Pd9-Data-Visualization-Maps
- https://delicious.com/dudarev

**Comment by dudarev** [comment]
@serejahh try to find ~5 examples of similar sites.

**Comment by serejahh** [comment]
@dudarev, something looks good?
- http://getpocket.com/a/queue/list/
- https://develop.re/
- http://asciiwwdc.com/
- https://developer.apple.com/library/ios/navigation/
- http://stackoverflow.com/questions/tagged/javascript
- https://www.ted.com/playlists/171/the_20_most_popular_talks_of_a
- http://apptractor.ru/UX/index.php
- https://hexlet.org/course/swift/

**Comment by dudarev** [comment]
They all look good. For our purpose https://develop.re/ seems like a good example.

Closing this ticket. But we should use it for reference in the future.

**Comment by dudarev** [comment]
Five site which design we could use in some way:
- http://startupmovies.be-genius.com
- http://top100.rambler.ru/navi/?theme=1
- http://urli.st/Pd9-Data-Visualization-Maps#section1-data-vis-general
- https://delicious.com/dudarev
- https://develop.re
