### ISSUE TITLE
Add links to password change pages

### ISSUE THREAD

**Issue by dudarev** [gromadco/change-password-links#2]
Please add 5 links to change password pages to `index.html`. Note that web site is stored in `gh-pages` branch. Pull repository and checkout that branch.

**Comment by dudarev** [comment]
@serejahh Please, also add 5 links to 5 services to `index.html`.

**Comment by dudarev** [comment]
Plan: 
- [ ] add 10 more services.

**Comment by dudarev** [comment]
List of services to add:
- [x] Yandex
- [x] Yahoo
- [x] Instagram
- [x] Vkontakte
- [x] Foursquare
- [x] Reddit
- [x] oDesk
- [x] Pinterest
- [x] Amazon
- [ ] 1
- [ ] 2
- [ ] 3

**Comment by Ku-Al** [comment]
- [x] Facebook
- [x] LinkedIn
- [x] Google
- [ ] Imena.ua
- [ ] Nic.ua
- [ ] PayPal
- [ ] Webmoney.ru

**Comment by ghost** [comment]
- [ ] Twitter
- [ ] GitHub (?)

**Comment by serejahh** [comment]
- [x] payoneer
- [x] [pocket](https://getpocket.com/changepass)
- [ ] [lingualeo](http://lingualeo.com/ru/profile/edit) (pick an icon to change)
- [ ] hexlet
- [x] coursera
- [ ] bitbucket
