### ISSUE TITLE
Initial simple design

### ISSUE THREAD

**Issue by dudarev** [gromadco/change-password-links#3]
Check examples of designs in

https://github.com/gromadco/change-password-links/issues/1#issuecomment-63533520

Make a simple initial design using

http://purecss.io/

**Comment by betula-pendula** [comment]
![20141202_150741](https://cloud.githubusercontent.com/assets/8578505/5262411/9ac0651c-7a36-11e4-915f-82c18df8f600.jpg)
![20141202_150814](https://cloud.githubusercontent.com/assets/8578505/5262412/9ac5e942-7a36-11e4-89a9-7174f2374315.jpg)
![20141202_150823](https://cloud.githubusercontent.com/assets/8578505/5262413/9ac82798-7a36-11e4-91eb-0f2878b908ef.jpg)

**Comment by dudarev** [comment]
The second one looks the best: https://cloud.githubusercontent.com/assets/8578505/5262412/9ac5e942-7a36-11e4-89a9-7174f2374315.jpg
