### ISSUE TITLE
Finalizing and cleaning up initial design

### ISSUE THREAD

**Issue by dudarev** [gromadco/change-password-links#5]
- [x] Alight header to the left
- [x] Icons, Text, Notes are on one line for one service
- [x] Add description
- [x] Add Google Analytics from gromad.co
- [x] Remove list of services that do not have direct links to password change form
- [x] Clean up repo
  - [x] remove unused css, js, images
  - [x] Add another text to `README.md`
  - [x] remove `index-example.html`

**Comment by betula-pendula** [comment]
I suppose that would be comments and suggestions
Therefore translate until Artem for review

**Comment by dudarev** [comment]
On mobile screens, make padding in main header similar to other content

![screen shot 2014-12-02 at 10 31 22](https://cloud.githubusercontent.com/assets/123531/5567211/4654a7c8-8f48-11e4-85c0-a2348d38871b.png)

**Comment by dudarev** [comment]
Do not use `h6` or any other header tag for non-header. Use more readable font (bold italic is not readable here). Make content wrap on small screens so that scrolling does not appear.

![screen shot 2014-12-02 at 10 32 40](https://cloud.githubusercontent.com/assets/123531/5567221/a977f1c0-8f48-11e4-9eb9-8cc4d356c4e7.png)

**Comment by dudarev** [comment]
Google Analytics code should be the same as on home gromad.co page. Remove extra property from analytics page.

**Comment by dudarev** [comment]
Three things remain to be done:
- [x] Main header
- [x] Help text for non-direct links
- [x] Google Analytics code

Please see three comments above.

**Comment by dudarev** [comment]
- [x] update description
- [x] give link to github to add more services

These are mostly for myself.
